name: Update Merval Sheet

on:
  schedule:
    - cron: '0,15,30,45 14-20 * * 1-5'  # Cada 15 min, Lun-Vie, 11:00-17:45 ART (14:00-20:45 UTC)
  workflow_dispatch:  # Permite ejecución manual

jobs:
  update-sheet:
    runs-on: ubuntu-latest
    env:
      GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        run: python analisis_merval.py
